Obr v2 5 1
IlyaKalosha/hl7conv pull request #3
Opened 2023-02-02 17:10 UTC by Zhauner

2023-02-02 18:37 UTC, Zhauner commented
Tt

2023-02-02 22:13 UTC, IlyaKalosha requested changes

2023-02-02 22:13 UTC, IlyaKalosha commented on hl7conv/schemas/versions/v2_5_1/enums.py
> +     O1_O9 = "O1 ... O9"
delete from code

2023-02-02 22:13 UTC, IlyaKalosha commented on hl7conv/schemas/versions/v2_5_1/enums.py
> +     W1_W4 = "W1 ... W4"
delete from code

2023-02-02 22:13 UTC, IlyaKalosha commented on hl7conv/schemas/versions/v2_5_1/enums.py
> +     _10_19 = "10 ... 19"
add each one separately and delete from code

2023-02-06 18:47 UTC, IlyaKalosha approved these changes

2023-02-06 18:55 UTC, IlyaKalosha approved these changes

2023-02-06 18:58 UTC, IlyaKalosha commented
- OBX v2_5_1 validation 
- enums v2_5_1
- validators v2_5_1
- complex structs v2_5_1
- GH actions with linters

2023-02-06 18:58 UTC, merged